### ISSUE TITLE
Missed data in the order tables

### ISSUE THREAD

**Issue by XxXgeoXxX** [MultiSafepay/magento2#12]
Preconditions: 
MSP - 2.3.0
Magento - 2.4.2

STR:
I haven't stable steps how to reproduce this bug. We faced it times by time in the next tables - sales_order_item, sales_order_payment  we have miss data for fields - qty_invoiced,  last_trans_id.
Point 1. Invoice was created order was paid, but qty_invoiced is 0
Point 2. In order comment transaction ID was set but after checking in the table this field was set as NULL

Could you please check why this can happened?
![ShowAttachImage (2)](https://user-images.githubusercontent.com/44254165/114509009-b5aec500-9c3d-11eb-9f88-47b52b143e2c.jpeg)
![Screenshot from 2021-04-13 09-47-12](https://user-images.githubusercontent.com/44254165/114509035-ba737900-9c3d-11eb-8f69-ae39f6e48677.png)

**Comment by vinodsowdagar** [comment]
Hi @XxXgeoXxX ,

Since version 2.3.0 we have introduced some changes to the webhooks to prevent this from happening. We recently released version 2.7.0: https://github.com/MultiSafepay/magento2/releases/tag/2.7.0 

Can you try to upgrade the plugin to the latest version and check if you are still encountering this issue?

**Comment by vinodsowdagar** [comment]
Hi @XxXgeoXxX ,

It has been a while since we heard from you. Do you still experience this issue?

**Comment by XxXgeoXxX** [comment]
Hi
We have updated the module. Looks like the problem was solved. Thank you
