### ISSUE TITLE
The payment method you requested is not available

### ISSUE THREAD

**Issue by alaaCrocoit** [MultiSafepay/magento2#34]
when i used this query 
query{
  multisafepayCart(cart_id:"kaDTle66fZjHrAjBxUnEA6NB8ep6hR3y"){
    available_payment_methods{
      title
    }
  }
}
this error show:
"The payment method you requested is not available"

**Comment by alaaCrocoit** [comment]
Magento ver. 2.4.4
and PWA ver:~12.2.0

**Comment by danielcivit** [comment]
Hello @alaaCrocoit 

Thanks for reach us and your report. 

- Did you check if the payment method is enabled? or if there is any restrictions that applies to the order placed, like min or max amount, and according the settings, the payment method should be disabled for those cases?

Looking forward to hear more from you.

**Comment by alaaCrocoit** [comment]
please can you tell me more info how can i check if the payment method is enabled

**Comment by alaaCrocoit** [comment]
<img width="900" alt="Screen Shot 2022-07-04 at 4 24 29 PM" src="https://user-images.githubusercontent.com/108675421/177174243-42b5ef60-293a-4c37-a957-5e5093bcf86b.png">
<img width="973" alt="Screen Shot 2022-07-04 at 4 29 30 PM" src="https://user-images.githubusercontent.com/108675421/177174931-92e4ec3f-5d20-4402-8c74-75a29cf69334.png">

please can you check screen shoots

**Comment by danielcivit** [comment]
Hello. 

It seems the payment methods are enable properly.  I have been testing the query you have shared.

I think the multisafepayCart only works when a MultiSafepay payment method has been set using 
setPaymentMethodOnCart. 

Otherwise, for a cart ID, in which the payment method is not set, you can use something like the following to get the available_payment_methods: 

```
query{
	cart(cart_id:"YOUR-CART-ID"){
		available_payment_methods{
			title
		}
	}
}
```


- Could you confirm if the above works for you?
- Could you let us know if you expect a different behavior using the multisafepayCart query, so we can check if we are doing something wrong?

 
Once again, thanks for reach us and for your report.

**Comment by alaaCrocoit** [comment]
Ok, how can i get selected_payment_method . it return empty text

**Comment by alaaCrocoit** [comment]
query{
  multisafepayCart(cart_id:"kaDTle66fZjHrAjBxUnEA6NB8ep6hR3y"){
    selected_payment_method{
      code
    }
  }
}

**Comment by vinodsowdagar** [comment]
Hi @alaaCrocoit ,

This query was only meant for retrieving a cart _after_ you have set the payment method on it. If the cart does not have a MultiSafepay payment method, it will probably return an error. This query was meant for doing operations which only should be executed if the customer paid with MultiSafepay, for example, to show a different success page.

If you would like to retrieve the cart before the payment method has been set, please refer to the original cart query from Magento: https://devdocs.magento.com/guides/v2.4/graphql/queries/cart.html

Since this does not seem to be an actual issue related with the module itself and more a question about how a specific query should work, i am closing this issue.

I hope everything is clear now. If you have more questions related to this topic, please send us an e-mail at integration@multisafepay.com and my colleagues from the integration team will help you further.
