### ISSUE TITLE
Critical error on Address::addCity()

### ISSUE THREAD

**Issue by GuidoHub** [MultiSafepay/magento2#42]
**Describe the bug**
main.CRITICAL: TypeError: Argument 1 passed to MultiSafepay\ValueObject\Customer\Address::addCity() must be of the type string, null given, called in /vendor/multisafepay/magento2-core/Model/Api/Builder/OrderRequestBuilder/CustomerBuilder/AddressBuilder.php on line 60 and defined in /vendor/multisafepay/php-sdk/src/ValueObject/Customer/Address.php:110

**To Reproduce**
Cannot really determine when this happens. I think maybe City is not filled by clients because it's not mandatory?

**Expected behavior**
Give error message in checkout

**Enviroment**
Magento 2.4.5-p1
Multisafepay 2.21.1

**Comment by vinodsowdagar** [comment]
Hi @GuidoHub ,

Thank you for the report.
We are going to look into this and come back to you later.

**Comment by vinodsowdagar** [comment]
Hi @GuidoHub , I've found that we are not accounting for the city argument in the OrderAddressInterface to be empty. The interface states that it always returns a string:

```
    /**
     * Gets the city for the order address.
     *
     * @return string City.
     */
    public function getCity();
```

Furthermore, i couldn't find any setting in Magento to make the city of the customer optional, so i am assuming this is a customisation which is not officially included in the Magento Framework.

It's fairly easy for us to support it anyway and i've added a backlog item to support it. It will be available in our next release.

Please note that if you are using Apple Pay, the customer city is required. 
So that payment method will most likely not work if the customer city is not filled it.

**Comment by GuidoHub** [comment]
@Vinod-MultiSafepay , I've have checked again but city is mandatory for both Shipping as Billing address. When I check the database Quote address I notice that City is empty. Need to figure out why the order process is not stopped because of this. I think the Payment process is triggered before checkout field check.

I am also using Mageplaza OnestepCheckout and Postcode plugin.

**Comment by vinodsowdagar** [comment]
Hi @GuidoHub ,

We have made some adjustments to make sure that the city is not mandatory any more, it has been released in the latest version: https://github.com/MultiSafepay/magento2/releases/tag/2.22.0

I'm closing this one for now. If you still find any problems, please let us know by replying to this issue or by creating a new one.
